version: "3.5"
services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - wp:/var/www/html
    depends_on:
      - wordpress
    networks:
      - incep_net
  wordpress:
    build: ./wordpress
    container_name: wordpress
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - wp:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - incep_net
  mariadb:
    build: ./mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    networks:
      - incep_net
networks:
  incep_net:
    name: incep_net
    driver: bridge

volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      type: none
      o: bind
      device: /home/hel-ayac/data/php
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /home/hel-ayac/data/mariadb


